CONUNDRUMS: list[tuple[str, str, str]] = [
("PACEANUS", "SAUCEPAN", "Heat it from the bottom."), 
("PORKSAWED", "SPADEWORK", ""), 
("ARSEMUFF", "EARMUFFS", "They'll keep you warm on a winter's day."), 
("PISSHOLE", "POLISHES", "You'll needto spray and rub repeatedly."), 
("NEATKNOB", "BANKNOTE", "Comes in different colours and sizes."), 
("RANDYBUSH", "HUSBANDRY", ""), 
("ACHYTITS", "CHASTITY", "Refraining from pleasure."), 
("DICKSPIT", "DIPSTICK", "Something long and covered in oil."), 
("ANALTIME", "LAMINATE", "You can overlay a surface."), 
("TWATCHOPS", "STOPWATCH", ""), 
("PEEPATIT", "APPETITE", "Craving something."), 
("YERRCOCK", "CROCKERY", "You need to give this a good wash after use."), 
("ARSELUBE", "REUSABLE", "You can use it more than once."), 
("ACNEGROIN", "GROINACNE", ""), 
("HARDSEMI", "MISHEARD", "Not always easy to grasp."), 
("LUBETITS", "SUBTITLE", "Making things easier."), 
("ARSEPROD", "EARDROPS", "Pop it in a hole."), 
("IWASHDONG", "SHADOWING", ""), 
("BUMHEADS", "AMBUSHED", "Taken by surprise."), 
("HUMPNICK", "CHIPMUNK", "A small, furry creature."), 
("MEGADICK", "MAGICKED", "Poof, now it's gone."), 
("SITONSEAN", "SENSATION", ""), 
("GONADTIP", "ADOPTING", "One way to become a parent."), 
("NOSEFART", "SEAFRONT", "Where you get a fresh breeze."), 
("LASTANUS", "SULTANAS", "Tastes fruity."), 
("ACLEANBUM", "AMBULANCE", ""), 
("SEANSBUM", "SUNBEAMS", "Brightens your day."), 
("TOOLFLAB", "FOOTBALL", "A lot of men are familiar with this."), 
("ITUGJONS", "JOUSTING", "Coming at me with his pole."), 
("GROPEYHAG", "GEOGRAPHY", ""), 
("GAVEHORN", "HANGOVER", "You might have this in the morning."), 
("LEESARSE", "RELEASES", "Just let it go."), 
("COCKTRAP", "CRACKPOT", "It's fun to have one of these around."), 
("DAMPUNCLE", "UNCLAMPED", ""), 
("HORNYMAC", "MONARCHY", "Extremely powerful."), 
("CUREDJON", "CONJURED", "You'll need magic to do this"), 
("BUMNOISES", "OMNIBUSES", ""), 
("FEELRHOD", "FREEHOLD", "He wants you to own him."), 
("PISSTOOL", "TOPSOILS", "It'll help it grow."), 
("ARSERASH", "HARASSER", "Get off my back!"), 
("GIANTNIPS", "PAINTINGS", ""), 
("LITESUCK", "LUCKIEST", "You'll be very fortunate."), 
("SADMILES", "MISLEADS", "I gave him the wrong impression."), 
("HELMSBIT", "THIMBLES", "It's the size of a fingertip."), 
("ISEETWATS", "AWEESTSAW", ""), 
("BUTTSCAR", "SUBTRACT", "Please take it away."), 
("LUBEDONG", "BLUDGEON", "Give it a whack."), 
("EATSHITE", "HESITATE", "Think twice about it"), 
("IRISHTART", "ARTHRITIS", ""), 
("SUCKTIME", "MUCKIEST", "Very filthy."), 
("APALEJON", "JALAPENO", "So hot."), 
("LADSHAPE", "SLAPHEAD", "Dara Ó Briain."), 
("OILYPANTS", "PONYTAILS", ""), 
("DEESRING", "REDESIGN", "He really should change it."), 
("NEATBUSH", "SUNBATHE", "Be careful, it could burn."), 
("TITSPOON", "SPITTOON", "Better out than in."), 
("FARTBAKES", "BREAKFAST", ""), 
("LOCKBUNS", "SUNBLOCK", "Rub it all over."), 
("GIMPTENT", "TEMPTING", "Hard to resist."), 
("KEVDROOP", "PROVOKED", "Poke a stick at it, see what happens."), 
("BEAUTJUGS", "SUBJUGATE", ""), 
("RUDENOBS", "REBOUNDS", "People like these after a break-up."), 
("HELLOPOO", "LOOPHOLE", "Help in a sticky situation."), 
("BUMFLING", "FUMBLING", "Just messing around."), 
("NOONEFART", "FONONETAR", ""), 
("NUDEFRED", "REFUNDED", "Get what you deserve."), 
("BUTTBASH", "BATHTUBS", "They can get a little dirty."), 
("SLAGNITE", "GENITALS", "A privateaffair."), 
("TWATREHAB", "BATHWATER", ""), 
("ASSGLORY", "GLOSSARY", "Look it up."), 
("SHAGBINS", "BASHINGS", "They can be very painful."), 
("RANDYBRA", "BARNYARD", "It can get a bit whiffy."), 
("PUBEALERT", "REPUTABLE", ""), 
("ASSBONER", "BARONESS", "A powerful position."), 
("SLAGPILE", "SPILLAGE", "Could get messy."), 
("DAMNBRAS", "ARMBANDS", "Tricky to get off."), 
("RENTAGIMP", "TAMPERING", ""), 
("STICKYJO", "JOYSTICK", "Will give you a good time."), 
("AWETROMP", "TAPEWORM", "Slips out of the backside."), 
("ASSCRANK", "RANSACKS", "Causes a lot of damage."), 
("LICKMESIR", "LIMERICKS", ""), 
("BEDSOWET", "BESTOWED", "A gift from me to you."), 
("CHEAPTIT", "PATHETIC", "Not very impressive."), 
("PENISROT", "PROTEINS", "Can be cheesy."), 
("MESCROTUM", "TREMMUCOS", ""), 
("BEDOSMAN", "ABDOMENS", "The harder the better."), 
("ARSEUNIT", "URINATES", "Needs relieving."), 
("RESTNUTS", "ENTRUSTS", "Put them in my hands."), 
("NOSEYTART", "ATTORNEYS", ""), 
("GOTOBANG", "TOBOGGAN", "Hop on and slide down."), 
("SNOGSPIT", "SIGNPOST", "Show me the way."), 
("DICKBASE", "BACKSIDE", "Sit on this."), 
("HOTMINGES", "SOMETHING", ""), 
("FANADONG", "FANDANGO", "It'll get you hot and sweaty."), 
("NOAHSTUD", "HANDOUTS", "He'll give it to anyone."), 
("WETNITES", "TWENTIES", "Not at his age."), 
("ODDBUMFUN", "DUMBFOUND", ""), 
("ACESPANK", "PANCAKES", "Give it a toss."), 
("TWATHERD", "THWARTED", "That'll stop him."), 
("DEERNUTS", "DENTURES", "Keep them in your mouth."), 
("SNOGAMILF", "FLAMINGOS", ""), 
("DATEDELF", "DEFLATED", "He went down on me."), 
("GRANFART", "FRAGRANT", "Smells lovely."), 
("FUNGIFTS", "STUFFING", "You can put it in your bird."), 
("IBEDSANTA", "ABSTAINED", ""), 
("LUBENUTS", "UNSUBTLE", "Don't make it obvious."), 
("TRIEDASS", "DISASTER", "It didn't go very well."), 
("NOSESCUM", "CONSUMES", "Eating it up."), 
("VASTBONER", "OBSERVANT", ""), 
("OILYBINT", "NOBILITY", "The Queen, for example."), 
("EATVOMIT", "MOTIVATE", "You can doit."), 
("NICEANUS", "NUISANCE", "It can get annoying."), 
("MOISTPITS", "OPTIMISTS", ""), 
("IAMINREG", "MIGRAINE", "This is really painful."), 
("NEATSHIT", "HESITANT", "Just go for it."), 
("ISPYMILF", "SIMPLIFY", "The easier the better."), 
("PENISBUMS", "BUMPINESS", ""), 
("OHMYKNOB", "HYMNBOOK", "Often held by a priest."), 
("ASSGAMES", "MASSAGES", "Loosen up the muscles."), 
("WOWDILDO", "WILDWOOD", "Not touched by human hands."), 
("RIDEVEGAS", "GRAVESIDE", ""), 
("BLUEDONG", "BLUDGEON", "Beat it repeatedly."), 
("VICYATIT", "ACTIVITY", "Things could get lively."), 
("BUMDATER", "DRUMBEAT", "Give it a tap."), 
("LONGWINKY", "KNOWINGLY", ""), 
("FINENUTS", "FUNNIEST", "Describes me perfectly."), 
("HOLDNIPS", "DOLPHINS", "They can do tricks."), 
("BONERAID", "DEBONAIR", "Well polished."), 
("BALLSTEAM", "MEATBALLS", ""), 
("HARDTUGS", "DRAUGHTS", "Fun to play with friends."), 
("FARTOBOE", "BAREFOOT", "Can cause a stink."), 
("NUTRIDER", "INTRUDER", "He'll give you quite a shock."), 
("STRAYDICK", "YARDSTICK", ""), 
("LICKPITS", "LIPSTICK", "Get this round your mouth."), 
("BAPFLICK", "BACKFLIP", "It takes a lot of practice."), 
("BALDNADS", "BADLANDS", "A dodgy area."), 
("TWATGAMES", "MEGAWATTS", ""), 
("NICEDONG", "ENCODING", "Nerds can't get enough of it."), 
("TASTEPOO", "POTATOES", "I like mine mashed."), 
("RHODTUGS", "DROUGHTS", "There's barely a trickle."), 
("NEEDAROMP", "PROMENADE", ""), 
("ANUSCAPE", "SAUCEPAN", "Covers the gas ring."), 
("OLDGROIN", "DROOLING", "I'm wet around the mouth."), 
("POKENUNS", "UNSPOKEN", "My little secret."), 
("RINGACHES", "SEARCHING", ""), 
("NEATPOOS", "TEASPOON", "The perfect mouthful."), 
("RINGGLOW", "GROWLING", "A sign that you're angry."), 
("MADBONER", "DOBERMAN", "It's really hard and scary."), 
("TITBANGER", "BANTERING", ""), 
("SOURTITS", "TOURISTS", "Always getting in the way."), 
("PUBERUGS", "SUPERBUG", "Very resistant."), 
("ANALMIST", "TALISMAN", "Brings me luck."), 
("MINGEBURN", "BURMINGEN", ""), 
("SEENDICK", "SICKENED", "Absolutely disgusting."), 
("POOPNEST", "POSTPONE", "I would give you ten minutes if I were you."), 
("MINGEAID", "IMAGINED", "Can you picture it?"), 
("NUDEPLUMS", "PENDULUMS", ""), 
("LICKTHIS", "TICKLISH", "It's really sensitive."), 
("HERPANTS", "PANTHERS", "They're dangerous to touch."), 
("RHODWANK", "HANDWORK", "It makes your wrist sore."), 
("NUTSGIRTH", "THRUSTING", ""), 
("IDOCRAPS", "SPORADIC", "Not very often."), 
("LICKNERD", "CRINKLED", "Ribbed for your pleasure."), 
("BUMNIGHT", "THUMBING", "You'll need to use your hands, no fingers allowed."), 
("WETGONADS", "DOWNSTAGE", ""), 
("BALLRISE", "LIBERALS", "Hang slightly to the left."), 
("SNOGATIT", "TOASTING", "I'll drink to that."), 
("ASSCOCKS", "CASSOCKS", "They're favoured by the clergy."), 
("MACHONIPS", "CHAMPIONS", ""), 
("TOPCOCKS", "STOPCOCK", "I've sprung a leak."), 
("PISSPLAY", "PAYSLIPS", "I look forward to it every month."), 
("TITRIDES", "DIRTIEST", "What a mess."), 
("DICKSTRUM", "DRUMSTICK", ""), 
("WETARSES", "SWEATERS", "Can be itchy."), 
("HEATNIPS", "THESPIAN", "Give them a play."), 
("PORNRAID", "RAINDROP", "Makes a wet patch."), 
("SOURBUTTS", "OUTBURSTS", ""), 
("WETNORKS", "NETWORKS", "The IT lads love them."), 
("EPICTURD", "PICTURED", "Just imagine it."), 
("BELLLUBE", "BLUEBELL", "This smells lovely."), 
("TWATLASER", "SALTWATER", ""), 
("ARSEGUFF", "SUFFRAGE", "It's a woman's right."), 
("LICKDUNG", "DUCKLING", "Delicious with some hoisin sauce."), 
("FLOPRAGE", "LEAPFROG", "I'm bent over waiting for you."), 
("IHUGBONER", "NEIGHBOUR", ""), 
("ARSEBIKE", "BAKERIES", "You'll get nice buns."), 
("GIMPHUNT", "THUMPING", "Can cause bruising."), 
("SOLOPARP", "PROPOSAL", "Put your finger in my ring."), 
("TITSHOWER", "SHITTOWER", ""), 
("KISSMEAT", "MISTAKES", "You'll always regret it."), 
("DAMPPOOP", "POPPADOM", "Comes with a curry."), 
("WANGRISE", "SWEARING", "How rude."), 
("SLIMYLUBE", "SUBLIMELY", ""), 
("MENSBUNS", "NUMBNESS", "Often gives me a tingle."), 
("WETAREAS", "SEAWATER", "Just dive right in."), 
("ANALLICE", "ALLIANCE", "You scratch my back, I'll scratch yours."), 
("MEATYSLAP", "PLAYMATES", ""), 
("TARTYELF", "FLATTERY", "Puts me in a good mood."), 
("GIMPSLED", "GLIMPSED", "I only got a flash."), 
("XMASLICE", "CLIMAXES", "I usually get these in bed."), 
("LEWDSANTA", "WASTELAND", ""), 
("GRABPIPE", "BAGPIPER", "Just squeeze the bag and blow."), 
("LETSFART", "FLATTERS", "It makes me feel good."), 
("GAYWANGS", "GANGWAYS", "Hello, sailor!"), 
("ORALPARTY", "PALATORRY", ""), 
("WANGITCH", "WATCHING", "Keep your eyes on the ball."), 
("FARTWOES", "SOFTWARE", "There's an app for that."), 
("ARANKGOO", "KANGAROO", "Commonly found in the bush."), 
("SPLITSACK", "SLAPSTICK", ""), 
("BOGSTAIN", "BOASTING", "Mine are incredible."), 
("SHYDILDO", "SHODDILY", "You're doing it all wrong."), 
("ANALPEST", "PLEASANT", "It's quite nice."), 
("LADYGROIN", "ROYALDING", ""), 
("PORNSLOG", "PROLONGS", "Keep it up for as long as you can."), 
("FIRMARSE", "FIREARMS", "Use responsibly."), 
("GROINTUG", "GROUTING", "It goes all over the bathroom."), 
("RANCIDGAS", "CARDIGANS", ""), 
("BUMSINGE", "BEMUSING", "It's a peculiar feeling."), 
("GRIPNUTS", "SPURTING", "Take aim and fire."), 
("ASSTRIPE", "RASPIEST", "That sounds rough."), 
("TURDFEARS", "FRAUDSTER", ""), 
("BOBSREAR", "ABSORBER", "It soaked up all the liquid."), 
("SADBONER", "BROADENS", "It's getting bigger."), 
("GUFFTINS", "STUFFING", "Get as much in as you can."), 
("ITCHYPISS", "PHYSICIST", ""), 
("FARTMORE", "REFORMAT", "Wipe clean and start again."), 
("SHAFTSIR", "STARFISH", "It's wet and pointy."), 
("NICEARSE", "INCREASE", "The bigger the better."), 
("MANSGIRTH", "HAMSTRING", ""), 
("SEMIDONG", "SMIDGEON", "It's only small."), 
("SEENTURD", "DENTURES", "Put it in your mouth."), 
("NIPSPLAY", "SNAPPILY", "Get straight to it."), 
("TENSEWANG", "NEWSAGENT", ""), 
("DONGHAIR", "HOARDING", "I've got a big collection."), 
("ASHYTURD", "THURSDAY", "It comes but once a week."), 
("MOISTTIP", "OPTIMIST", "One can only hope."), 
("TIREDHUMP", "TRIUMPHED", ""), 
("DRABORAL", "LABRADOR", "Man's best friend."), 
("SEMITOSS", "MOSSIEST", "Damp to the touch."), 
("DOGSMEAR", "ORGASMED", "Wipe it down afterwards."), 
("WILLYGONE", "YELLOWING", ""), 
("LONGTITS", "SLOTTING", "Just fit them in."), 
("FREEDUMP", "PERFUMED", "Smells beautiful."), 
("GROSSLAY", "GLOSSARY", "Susie loves it."), 
("MAGICPORN", "COMPARING", ""), 
("FARTCURE", "FRACTURE", "You better see the doctor."), 
("TOSSMINE", "MOISTENS", "Get it wet."), 
("PENISGUN", "PENGUINS", "I keep mine in the kitchen cupboard."), 
("TIGERANUS", "SIGNATURE", ""), 
("CHESTRUB", "BUTCHERS", "Loves handling flesh."), 
("ANUSMIST", "TSUNAMIS", "Could get you wet."), 
("GRINDMUM", "DRUMMING", "Requires both hands."), 
("RECTALSIP", "CLAPTIRES", ""), 
("ARSESOLO", "AEROSOLS", "Full of gas."), 
("GENITALS", "STEALING", "Don't touch the crown jewels."), 
("TITCHESS", "STITCHES", "It'll hurt."), 
("BADGROINS", "DISROBING", ""), 
("WETGROIN", "TOWERING", "Can be pretty imposing."), 
("SLUTBITE", "SUBTITLE", "Seen but not heard."), 
("STIFFGUN", "STUFFING", "Force itinto your trousers."), 
("MERCYSHIT", "CHEMISTRY", ""), 
("DAILYSEX", "DYSLEXIA", "Don't put your 'D' in the wrong place."), 
("FEELDUNG", "ENGULFED", "I'm covered in it."), 
("PINGTITS", "SPITTING", "My mum hates me doing this."), 
("HATEWILLY", "WEALTHILY", ""), 
("HUNGTOSS", "GUNSHOTS", "Aim and fire."), 
("SPITRASH", "HARPISTS", "Give it a pluck."), 
("PISSLOAD", "DISPOSAL", "Get rid of it."), 
("EATENTURD", "UNTREATED", ""), 
("OAPPERVS", "APPROVES", "It's a thumbs up from me."), 
("ARSECRUD", "CRUSADER", "Holy shit."), 
("ISEEPORN", "PIONEERS", "Who came first?"), 
("TRUEFARTS", "FRUSTRATE", ""), 
("MEATRIDE", "DIAMETER", "It's all about the girth."), 
("DIRENIPS", "INSPIRED", "That's given me an idea."), 
("PAIDSLUT", "PLAUDITS", "They've earned it."), 
("WETNUDIST", "UNTWISTED", ""), 
("GIRTHFAN", "FARTHING", "Makes me think of grandma."), 
("NIPSRISE", "INSPIRES", "That gives me an idea."), 
("TOSSRACE", "COASTERS", "Don't leave any stains."), 
("GUFFSIREN", "SUFFERING", ""), 
("POOFORTS", "ROOFTOPS", "Climb up and enjoy the view."), 
("TOSSTIME", "MOISTEST", "Always gets me wet."), 
("TAKENBUM", "BUNKMATE", "Bagsy on top."), 
("TIGHTSEMI", "MIGHTIEST", ""), 
("SHAGNOEL", "HALOGENS", "A real turn on."), 
("TINSELHO", "HOTLINES", "Call me."), 
("POOFROST", "ROOFTOPS", "Watch your step, Santa."), 
("ELFDICKER", "FLICKERED", ""), 
("HISTIFFY", "FIFTYISH", "Gets better with age."), 
("HEFARTED", "FATHERED", "As only a man can."), 
("TITFEAST", "FATTIEST", "The bigger the better."), 
("LOSTPENIS", "POINTLESS", ""), 
("NEONPISS", "PENSIONS", "My grandma gets it once a week."), 
("ILOVESAC", "VOCALISE", "And I'm not afraid to say it."), 
("BUTTRISE", "TRIBUTES", "I'm incredibly moved."), 
("DENTPOOPS", "POSTPONED", ""), 
("LIKEWANG", "WEAKLING", "A bit soft."), 
("TITSLUBE", "SUBTITLE", "My gran needs this."), 
("LADYPISS", "DISPLAYS", "What a great show."), 
("SHAGINBUM", "AMBUSHING", ""), 
("GIANTLOG", "GLOATING", "I'm just showing off."), 
("TASTENIP", "PATIENTS", "There's probably a waiting list."), 
("WILLYGONG", "GOLLYWING", ""), 
("NOBCURSE", "BOUNCERS", "You don't want to be hit by one."), 
("TUGONNIP", "GUNPOINT", "Put your hands where I can see them."), 
("SEXPILOT", "EXPLOITS", "Ready for an adventure."), 
("MONEYTITS", "TESTIMONY", ""), 
("IDLEBLOW", "BILLOWED", "Give it a puff."), 
("TURDCAPE", "CAPTURED", "I've got it."), 
("RUDEDONG", "GROUNDED", "Not allowed to come out."), 
("BUMLINGER", "LUMBERING", ""), 
("NUDESNOG", "DUNGEONS", "They're wet and dirty."), 
("THINARSE", "HAIRNETS", "Full of short and curlies."), 
("RUBSADLY", "ABSURDLY", "This feels weird."), 
("BONEGIRTH", "BOTHERING", ""), 
("MOISTONE", "EMOTIONS", "You might need a tissue."), 
("MICROSEX", "EXORCISM", "Somebody call a priest."), 
("DIRTYBASH", "BIRTHDAYS", ""), 
("ABELLEND", "LENDABLE", "You can have it, but I'll need it back."), 
("SUCKPITS", "STICKUPS", "Put your hands above your head."), 
("LETSPUMP", "PLUMPEST", "It's big and juicy."), 
("NICESHITS", "ITCHINESS", ""), 
("VOTEARSE", "OVEREATS", "Shove it all in."), 
("SHITPOLL", "HILLTOPS", "The only way is up."), 
("IVOTEPISS", "POSITIVES", ""), 
("NEATPOLE", "ANTELOPE", "Watch out for the horn."), 
("ORALNITE", "RELATION", "Keep it in the family."), 
("POOPSITES", "OPPOSITES", ""), 
("SENDBUMS", "DUMBNESS", "I like them thick."), 
("PENISTIP", "NIPPIEST", "Fancy a quick one."), 
("IDLEPOOS", "POOLSIDE", "My favourite way to relax."), 
("DEADBONER", "BROADENED", ""), 
("NOBALARM", "ABNORMAL", "That's not right."), 
("WETRIDES", "WEIRDEST", "Things are about to get crazy."), 
("IBUMPETS", "BUMPIEST", "Not a smooth ride."), 
("BESTGIRTH", "BRIGHTEST", ""), 
("HUNGNADS", "HANDGUNS", "Fully loaded."), 
("AMPLESEX", "EXAMPLES", "Show me how you do it."), 
("TESTSWEE", "SWEETEST", "How's it taste?"), 
("NERDYTITS", "DENTISTRY", ""), 
("SNOTGUSH", "SHOTGUNS", "Take aim and fire."), 
("NOBISRAW", "RAINBOWS", "It's all kinds of colours."), 
("PURESLAG", "EARPLUGS", "Keep thenoise down."), 
("FEELTURDS", "LEEFTURDS", ""), 
("NAKEDWEE", "WEAKENED", "I feel vulnerable."), 
("IDEATNOB", "OBTAINED", "When I get my hands on it."), 
("SEALPORN", "PERSONAL", "For my private collection."), 
("ODDWANGER", "DOWNGRADE", ""), 
("RIDEBUNS", "SIDEBURN", "Those cheeks are hairy."), 
("SLICKTIP", "LIPSTICK", "Mine's bright red."), 
("CRAPSITE", "PRACTISE", "I do it over and over again."), 
("ITASTEVOM", "MOTIVATES", ""), 
("MRSBULGE", "GRUMBLES", "She's a real moaner."), 
("OHSLAPIT", "HOSPITAL", "Then call me an ambulance."), 
("DICKMIME", "MIMICKED", "You copied me."), 
("SITSINPOO", "POSITIONS", ""), 
("ANGELASS", "LASAGNES", "Hot and tasty."), 
("SHITNOEL", "HOTLINES", "Then call these numbers."), 
("SNOWDICK", "WINDSOCK", "Up and breezy."), 
("ASSTINSEL", "STAINLESS", ""), 
("MOOBWORK", "BOOKWORM", "Susie loves these."), 
("IHITARSE", "HAIRIEST", "But only the furry ones."), 
("NOBBURST", "STUBBORN", "That'll be hard to shift."), 
("COVERNIPS", "PROVINCES", ""),
("NUDEREST", "DENTURES", "My nan loves hers."), 
("SLIMPOLE", "PLIMSOLE", "You see a lot of them in the gym."), 
("LONEBUTT", "UNBOTTLE", "Pop out the plug."), 
("IGOTBONER", "REBOOTING", ""), 
("PERTALAN", "PATERNAL", "Who's your Daddy?"), 
("SWEETBOD", "BESTOWED", "Give it to me."), 
("NOSHHERO", "SHOEHORN", "Stuffs it all in."), 
("HOTMINGER", "MOTHERING", ""), 
("IRUBRASH", "AIRBRUSH", "That'll clear up nicely."), 
("ORGYMEET", "GEOMETRY", "Make sure you've got the right angle."), 
("ASSSERUM", "MASSEURS", "Grease me up."), 
("LARGENIPS", "RELAPSING", ""), 
("LITESEXT", "TEXTILES", "I've got a lot of material."), 
("ICANTPEE", "PATIENCE", "Have another go."), 
("HECREAMS", "CASHMERE", "So soft on my skin."), 
("DICKQUEEN", "QUICKENED", ""), 
("FREESHAT", "FEATHERS", "Ooh, that tickles."), 
("BUMCOSTS", "COMBUSTS", "It's gonna blow."), 
("GIMPSKIN", "SKIMPING", "It's value for money."), 
("HIDETRUMP", "TRIUMPHED", ""), 
("GRIMALAN", "ALARMING", "He's quite disturbing."), 
("AMINGEIS", "IMAGINES", "Anything you want it to be."), 
("PLAINSEX", "EXPLAINS", "Tell me more."), 
("DRAWNCOCK", "COCKDRAWN", ""), 
("FARTLINE", "INFLATER", "Get ready to blow."), 
("LASTNUDE", "UNSALTED", "It won't leave a taste in your mouth."), 
("TITCAKES", "TACKIEST", "Now that's just bad taste."), 
("DONGWIPER", "POWDERING", ""), 
("WANGTITS", "SWATTING", "Just bat them away."), 
("NAKEDPIC", "PANICKED", "Something to worry about."), 
("KNOBDOSE", "BOOKENDS", "Take one at both ends."), 
("EARLYSHIT", "REALYSHIT", ""), 
("SPURTSIR", "STIRRUPS", "Legs in the air, please."), 
("CRUDEJON", "CONJURED", "That came out of nowhere."), 
("LIMPAUNT", "PLATINUM", "Worth every penny."), 
("ABUMRINSE", "SUBMARINE", ""), 
("ASWINGER", "SWEARING", "How very dare you!"), 
("JOECRIED", "REJOICED", "It made me happy."), 
("BAREBODS", "ABSORBED", "Soak it all in."), 
("PENISTALE", "PENALTIES", ""), 
("FLOPRISE", "PROFILES", "Looks better from the side."), 
("SUAVEROD", "SAVOURED", "Enjoy every bit of it."), 
("SHITYEAR", "HYSTERIA", "Calm down and get over it!"), 
("REARGULLY", "REGULARLY", ""), 
("ELFROAST", "FLOATERS", "Didn't go down well."), 
("ELVESROD", "RESOLVED", "Get it all straight and done."), 
("ANUTROAST", "ASTRONAUT", ""), 
("ABANGSIR", "BARGAINS", "It's a great deal."), 
("NEEDPISS", "DISPENSE", "Let it all out."), 
("SHITFEET", "HEFTIEST", "They're just too big."), 
("NICERANUS", "INSURANCE", ""), 
("LESSLIMP", "MISSPELL", "Susie won't be happy."), 
("GENTSEMI", "MEETINGS", "Let's book a room."), 
("ITCHMESS", "CHEMISTS", "You're going to want some cream for that."), 
("AUNTGROAN", "ORANGUTAN", ""), 
("NICEGRIP", "PIERCING", "You may feel a small prick."), 
("NIPSEDGE", "SPEEDING", "Let's take things slow."), 
("RADMINGE", "DREAMING", "I do it in bed."), 
("ORGIESHUT", "RIGHTEOUS", ""), 
("FALSENIP", "LIFESPAN", "We've all got one."), 
("IRATENOB", "BARITONE", "It's a low blow."), 
("CATMINGE", "MAGNETIC", "Both attractive and replusive."), 
("WANGERSIN", "ANSWERING", ""), 
("ROBPERVS", "PROVERBS", "Teach him a lesson."), 
("LUBEDSIR", "BUILDERS", "Would you like an extension?"), 
("PISSLANE", "PAINLESS", "That feels nice."), 
("AFARTWELL", "WATERFALL", ""), 
("FARTGLUE", "GRATEFUL", "Thank you very much."), 
("GROINTAN", "IGNORANT", "That was bliss."), 
("SADREACH", "CHARADES", "Hope you're good with your hands."), 
("RANDYFLOG", "DRAGONFLY", ""), 
("LICKBONG", "BLOCKING", "Stop that right now."), 
("ACEHOLES", "SHOELACE", "Put a bow in it."), 
("COCKBEAM", "COMEBACK", "Nice to see you again."), 
("CRUDEFART", "FRACTURED", ""), 
("LESSBUTT", "SUBTLEST", "Be discrete."), 
("FIREPLOP", "FLOPPIER", "Not as hard as you thought."), 
("RIPENADS", "SPRAINED", "See your doctor."), 
("LICKSDUNG", "DUCKLINGS", ""), 
("CAGENIPS", "ESCAPING", "Get them out."), 
("SHOWPORK", "WORKSHOP", "Make sure you've got wood."), 
("LUBEKITS", "BULKIEST", "The bigger, the better."), 
("PERTGONAD", "GODPARENT", ""), 
("ODDPILES", "LOPSIDED", "That doesn't feel right."), 
("REDGROIN", "ORDERING", "I asked for it."), 
("IDLENUTS", "INSULTED", "How rude."), 
("GROINPOPS", "PROPOSING", ""), 
("REDMOOBS", "BEDROOMS", "Where the magic happens."), 
("ORGYHUTS", "YOGHURTS", "It's only natural."), 
("SPLATGOO", "GOALPOST", "Stop whacking it."), 
("CAMELSHIT", "ALCHEMIST", ""), 
("URINEPOT", "ERUPTION", "It's bubbling over."), 
("HOTPENIS", "PHONIEST", "It can't be real."), 
("ARSEPOET", "OPERATES", "Handle with care."), 
("USEDORGAN", "DANGEROUS", ""), 
("NEEDTUSH", "ENTHUSED", "Yes please!"), 
("PENISART", "PAINTERS", "Good to decorate your house."), 
("BONKLIST", "INKBLOTS", "This could get messy."), 
("ELFSTAIN", "INFLATES", "It's getting bigger."), 
("NUTTYLOG", "GLUTTONY", "I want more."), 
("ICEORALS", "CALORIES", "I've had too many."), 
("INSERTNUT", "NUTRIENTS", ""), 
("HORNLICE", "CHLORINE", "This should get rid of them."), 
("DIREFART", "DRAFTIER", "It's really windy."), 
("NEATBONK", "BANKNOTE", "Everyone loves these."), 
("IDIOTANUS", "AUDITIONS", ""), 
("NICERODS", "CONSIDER", "I'll think about it."), 
("RARESHIT", "TRASHIER", "Tackier than normal."), 
("EARPLOPS", "PROLAPSE", "This happened to my anus."), 
("NIPSHAPES", "HAPPINESS", ""), 
("DRAGNADS", "GRANDADS", "Mine are all wrinkled."), 
("GLUMNIPS", "SLUMPING", "They're hanging low."), 
("SNIFFTUG", "STUFFING", "Smells like onions."), 
("GROINTAPE", "OPERATING", ""),
("DONGIDOL", "DOODLING", "I like to draw them."), 
("ANTIORAL", "RATIONAL", "That's reasonable."), 
("SOFTRING", "FROSTING", "Ooh, yummy!"), 
("BAREMILES", "MISERABLE", ""), 
("CLEANROD", "COLANDER", "Mine's full of holes."), 
("NUDELIST", "INSULTED", "How dare you!"), 
("SLIPANUT", "NUPTIALS", "You always need two."), 
("MINTYORAL", "ROYALMINT", ""), 
("DONGEXIT", "DETOXING", "I feel better already."), 
("NEATPARP", "APPARENT", "There's no hiding it."), 
("LUBERODS", "BOULDERS", "These are big and heavy."), 
("BOREDWANK", "BREAKDOWN", ""), 
("WANGLILO", "ALLOWING", "Can I have a go?"), 
("BITEDUNG", "DEBUTING", "There's a first time for everything."), 
("ECOFARTS", "FORECAST", "It might get windy."), 
("DONGSWEAT", "DOWNSTAGE", ""), 
("IDRYNUTS", "INDUSTRY", "It's hard work."), 
("LICKSHIT", "TICKLISH", "It will make you smile."), 
("KNOBSGOO", "SONGBOOK", "Sounds good to me."), 
("TOMSBONER", "TROMBONES", ""), 
("EROTICME", "METEORIC", "It's out of this world."), 
("WASHSACK", "HACKSAWS", "Make sure you've got a firm grip."), 
("EDGYHORN", "HYDROGEN", "This could explode."), 
("EATINGFUR", "FEATURING", ""), 
("ICEDDONG", "DECODING", "You can crack it."), 
("SLYSANTA", "ANALYSTS", "He's checking it twice."), 
("YULEWIND", "UNWIELDY", "That's a heavy one."), 
("MINCEPOLE", "POLICEMEN", ""), 
("DREROTIC", "DIRECTOR", "He calls the shots."), 
("PIPERASH", "SAPPHIRE", "I gave one to my partner."), 
("ASSSEEDS", "ASSESSED", "Let me have a look."), 
("GETORGASM", "MORTGAGES", ""), 
("NUTSBURN", "SUNBURNT", "There's a cream for that."), 
("ORALPOPS", "PROPOSAL", "She saidyes."), 
("DONGDRIP", "PRODDING", "I felt that."), 
("IDEALSNOG", "LOSEADING", ""), 
("TOSSPIPE", "SOPPIEST", "That was emotional."), 
("EATSSHIT", "HASTIEST", "Not so fast."), 
("SIRIBANG", "BRAISING", "Now we're cooking."), 
("UNCLETART", "RELUCTANT", ""), 
("NUTSHERO", "SOUTHERN", "I'm heading down."), 
("ANUSTRIM", "NATURISM", "It's all on show."), 
("ORALBITS", "ORBITALS", "Just go round and round."), 
("BALLSERUM", "UMBRELLAS", ""), 
("TURDPISS", "DISRUPTS", "It's coming whether you like it or not."), 
("ASSRELIC", "CLASSIER", "Age like a fine wine."), 
("ABADTOOL", "BOATLOAD", "Full of seamen."), 
("PENISTOUR", "ERUPTIONS", ""), 
("NIPPYGAL", "APPLYING", "Put some cream on it."), 
("SHITETIP", "PITHIEST", "The shorter the better."), 
("ERECTSEX", "EXCRETES", "It's seeping out."), 
("SEEBRATIT", "BATTERIES", ""), 
("HESHARTS", "HARSHEST", "Worst Christmas dinner ever."), 
("GIFTHORN", "FROTHING", "It looks like it's bubbling."), 
("GASSYLEE", "EYEGLASS", "What a lovely present."), 
("GIFTORNIP", "PROFITING", ""), 
("TURDPOSE", "SPROUTED", "It's popping out."), 
("RODINGOB", "BROODING", "I need to think about that."), 
("MINGEAIR", "MIGRAINE", "It'll blow your vision."),
("IFEELCRAP", "FIREPLACE", ""), 
("TIESWANG", "SWEATING", "It's getting hot in here."), 
("TOMSHOSE", "SMOOTHES", "Not a single wrinkle."), 
("IPEGNUNS", "PENGUINS", "I pick them up."), 
("DAMPPOOPS", "POPPADOMS", ""), 
("SMUTAREA", "AMATEURS", "I don't know what I'm doing."), 
("BESTSACK", "SETBACKS", "There might be some wrinkles."), 
("DICKTIPS", "DIPSTICK", "Oil me up."), 
("MINGEPARP", "PAMPERING", ""), 
("PEESTING", "STEEPING", "Try soaking it."), 
("POOSTING", "STOOPING", "Try bending over."), 
("NUTSTING", "STUNTING", "Mine are tiny."), 
("LEESHARTS", "HEARTLESS", ""), 
("BOOBLEAK", "BOOKABLE", "I'm available."), 
("CRAPHERE", "PREACHER", "Don't tell me what to do."), 
("CUTSPERM", "CRUMPETS", "Lovely with some melted butter."), 
("BASHEDNUT", "SUNBATHED", ""), 
("PRIMTUSH", "TRIUMPHS", "I'm proud of mine."), 
("IPLANSEX", "EXPLAINS", "I'll talk you through it."), 
("CARRNUTS", "CURRANTS", "Nom, nom, nom, nom, nom, nom, nom, nom, nom."), 
("RUDEDONGS", "UNDERDOGS", ""), 
("GNAWNIPS", "WINGSPAN", "The wider, the better."), 
("FEEDITIN", "DEFINITE", "This will work."), 
("RICOSHAT", "CHARIOTS", "It's on fire."), 
("LUBEDNERD", "BLUNDERED", ""), 
("GIANTNIP", "PAINTING", "Put that on display."), 
("ADIMRING", "ADMIRING", "I can't stop looking at it."), 
("OOHAWMRS", "WASHROOM", "Give it a good clean."), 
("GONADUSER", "DANGEROUS", ""), 
("ITSMRPOO", "IMPOSTOR", "Areyou sure?"), 
("ONESPUNK", "UNSPOKEN", "Holding some back."), 
("TITSROOM", "MOTORIST", "Get into gear."), 
("MOISTNERD", "MODERNIST", ""), 
("DICKDOSE", "DOCKSIDE", "Hello, sailor."), 
("HELDSACK", "SHACKLED", "Ooh, that's a bit tight."), 
("WEALLFART", "WATERFALL", ""), 
("WIPEDNIP", "WINDPIPE", "Take a deep breath."), 
("THECRAPS", "CHAPTERS", "One more before bed."), 
("WANKTIRE", "KNITWEAR", "It's starting to itch."), 
("TALLPENIS", "PANELLIST", ""), 
("ORALDIET", "TAILORED", "It suits me well."), 
("ARSETWIT", "WARTIEST", "It's horrible to look at."), 
("FERALTUG", "GRATEFUL", "That was lovely, thank you."), 
("SHITFACED", "CATFISHED", ""), 
("ICEPLOPS", "POPSICLE", "Give it a lick."), 
("ELFPARPS", "FLAPPERS", "That wafts."), 
("PEGSANTA", "PAGEANTS", "A bit showy."), 
("TIREDSACK", "SIDETRACK", ""), 
("AHIRNIPS", "HAIRPINS", "Grip it tight."), 
("RUBSAHIR", "AIRBRUSH", "Not a wrinkle in sight."), 
("AHIRDONG", "HOARDING", "Can't get enough."), 
("SHAGINBIN", "BANISHING", ""), 
("ITSANOSH", "ASTONISH", "Wow, that's amazing."), 
("SORTLUBE", "TROUBLES", "I've got problems."), 
("ARSEICON", "SCENARIO", "Picture this."), 
("WANGDINER", "WANDERING", ""), 
("LAYCLAUS", "CASUALLY", "No strings attached."), 
("RIMSANTA", "TAMARINS", "What a cheeky monkey!"), 
("ANGELNUTS", "UNTANGLES", ""), 
("STRIPLEE", "REPTILES", "Looks a bit scaly."), 
("TITCARDS", "DISTRACT", "I can'tstop looking at them."), 
("FINALTUG", "FAULTING", "This isn't working."), 
("LETMEDUMP", "PLUMMETED", ""), 
("MEDOCRAP", "COMPARED", "Mine's bigger than yours."), 
("SNOGSTIP", "SIGNPOST", "Show methe way."), 
("OWNSDICK", "WINDSOCK", "Mine's blowing all over the place."), 
("POOCRATER", "CORPORATE", ""), 
("BATHEROB", "BATHROBE", "Works best if you're naked."), 
("PURETURD", "RUPTURED", "What a mess."), 
("HESTRIPS", "HIPSTERS", "It's a hairy one."), 
("WANGRIDER", "REWARDING", ""), 
("RODBALLS", "BOLLARDS", "They're hard as concrete."), 
("SHITSFAR", "STARFISH", "It's a wet one."), 
("IBANGROD", "BOARDING", "Everyone jump on."), 
("SNOGMAYBE", "MONEYBAGS", ""), 
("WILLYFLU", "WILFULLY", "I got it deliberately."), 
("TUNALIPS", "NUPTIALS", "You may now kiss the bride."), 
("TRYLUBES", "BLUSTERY", "It's windy down there."), 
("CALMSHITE", "ALCHEMIST", ""), 
("IFHERUBS", "BUSHFIRE", "There'll be sparks."), 
("GOONSHIT", "SOOTHING", "Does that feel better?"), 
("MINGEDIP", "IMPEDING", "Get out of the way."), 
("ISHAGNERD", "GARNISHED", ""), 
("SEMITOUR", "MOISTURE", "It's gone all soggy."), 
("ARSENUTS", "SAUNTERS", "Slowly does it."), 
("SHITRUMP", "TRIUMPHS", "Give me a medal."), 
("GOINGPISS", "GOSSIPING", ""), 
("GONADNIT", "DONATING", "Better to give than to receive."), 
("INTOALAN", "NATIONAL", "Do it for your country."), 
("WANKRISE", "SWANKIER", "That's a posh one."), 
("LIMPGROIN", "IMPLORING", ""), 
("OWNGIRTH", "THROWING", "You night need two hands."), 
("TAPEARSE", "SEPARATE", "They're moving apart."), 
("ACHYLIPS", "PHYSICAL", "No time for talking."), 
("IDONEDUMP", "IMPOUNDED", ""), 
("IHOGNUTS", "SHOUTING", "Keep your mouth closed."), 
("ASSBLEND", "BALDNESS", "Not a hair in sight."), 
("MOISTPIE", "OPTIMISE", "Make the most of it."), 
("WEALLPARP", "WALLPAPER", ""), 
("IDOGALAN", "DIAGONAL", "Make sure you've got the right angle."), 
("SARAHNIP", "PIRANHAS", "Be careful, they bite."), 
("GOTSEMEN", "GEMSTONE", "That's priceless."), 
("MINGERUST", "MUSTERING", ""), 
("PENISGEL", "SLEEPING", "Lie back and close your eyes."), 
("SOURBUTT", "OUTBURST", "That was strong."), 
("SODOIRUB", "BOUDOIRS", "Keep it in the bedroom."), 
("RINSEWANG", "ANSWERING", ""), 
("SWINGPEE", "SWEEPING", "In one smooth motion."), 
("SADSHITE", "SHADIEST", "Looks a bit suspect."), 
("OOPSCLAP", "ALCOPOPS", "I've got it down the pub."), 
("THICKWANG", "THWACKING", ""), 
("TOSSDYER", "DESTROYS", "There's nothing left."), 
("ASSCUTIE", "SAUCIEST", "It's all gravy."), 
("BLOWNBIG", "WOBBLING", "I'm turning to jelly."), 
("PENISROTA", "PATRONISE", ""), 
("IWETSACK", "WACKIEST", "That was crazy."), 
("ARATCOCK", "COATRACK", "It's where Jon hangs his hat."), 
("MINGEBUS", "BEMUSING", "How does that work?"), 
("NICEARSES", "INCREASES", ""), 
("RINSEBOB", "SNOBBIER", "Don't look down."), 
("TOMFARTED", "FORMATTED", ""), 
("RHODWEES", "SHOWERED", "Hand me a towel."), 
("WHYISHAG", "HIGHWAYS", "For a fast ride."), 
("NOBCREAM", "BROMANCE", "Enjoy it withother guys."), 
("ASSREGION", "GROINAREA", ""), 
("RINGALEX", "RELAXING", "For a good time."), 
("NICERSHAG", "SEARCHING", ""), 
("SOFTPHIL", "SHOPLIFT", "Keep your hands where I can see them."), 
("ALOTITTY", "TOTALITY", "It's everything to me."), 
("NERDTUSH", "THUNDERS", "I hear it rumbling."), 
("LIKESWANG", "WEAKLINGS", ""), 
("ADORETUG", "OUTRAGED", "I've gone red in the face."), 
("IBAREASS", "AIRBASES", "Get ready for takeoff."), 
("LICKSTIP", "LIPSTICK", "It's gone all red."), 
("DEEPLOVER", "DEVELOPER", "")
]
